# Generated by Django 5.1.3 on 2024-11-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Review', models.TextField()),
                ('Sentiment', models.CharField(max_length=20)),
                ('Model_Prediction', models.CharField(max_length=20)),
            ],
        ),
    ]
