# Generated by Django 5.1.3 on 2024-11-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodlens_ml_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewdatamodel',
            name='Cleaned_Review',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
